version: '3'
services:
  mysql:
    image: "mysql:latest"
    container_name: web-solutions-database
    ports:
      - "3306:3306"
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: An1m@Rum@2000
      MYSQL_DATABASE: users
    volumes:
      - ./latest-version.sql:/docker-entrypoint-initdb.d/latest-version.sql
    command: --default-authentication-plugin=mysql_native_password